# Generated by Django 6.0.2 on 2026-02-17 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('value_type', models.CharField(choices=[('bool', 'Boolean'), ('int', 'Integer'), ('json', 'JSON')], default='bool', max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=False)),
                ('value_json', models.JSONField(blank=True, default=dict)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_mappings', to='featureflags.featurecatalog')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_mappings', to='subscriptions.subscriptionplan')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('plan', 'feature'), name='uniq_plan_feature_mapping')],
            },
        ),
        migrations.CreateModel(
            name='TenantFeatureOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=False)),
                ('value_json', models.JSONField(blank=True, default=dict)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_overrides', to='featureflags.featurecatalog')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_overrides', to='tenants.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant', 'feature'), name='uniq_tenant_feature_override')],
            },
        ),
    ]
