# Generated by Django 6.0.2 on 2026-02-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturesPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(choices=[('ar', 'Arabic'), ('en', 'English')], default='ar', max_length=8, unique=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('subtitle', models.TextField(blank=True)),
                ('cards', models.TextField(blank=True, help_text='One card per line. Format: Title|Description. Example: Cloud POS|Fast cashier workflows.')),
                ('closing_title', models.CharField(blank=True, max_length=255)),
                ('closing_text', models.TextField(blank=True)),
                ('closing_cta', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'ordering': ['language'],
            },
        ),
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(choices=[('ar', 'Arabic'), ('en', 'English')], default='ar', max_length=8, unique=True)),
                ('kicker', models.CharField(blank=True, max_length=140)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('subtitle', models.TextField(blank=True)),
                ('primary_cta', models.CharField(blank=True, max_length=120)),
                ('secondary_cta', models.CharField(blank=True, max_length=120)),
                ('problem_title', models.CharField(blank=True, max_length=255)),
                ('problem_text', models.TextField(blank=True)),
                ('solution_text', models.TextField(blank=True)),
                ('highlights', models.TextField(blank=True, help_text='One line per highlight item.')),
                ('metrics', models.TextField(blank=True, help_text='One line per metric item.')),
                ('final_title', models.CharField(blank=True, max_length=255)),
                ('final_text', models.TextField(blank=True)),
                ('final_cta', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'ordering': ['language'],
            },
        ),
        migrations.CreateModel(
            name='PricingPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(choices=[('ar', 'Arabic'), ('en', 'English')], default='ar', max_length=8, unique=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('subtitle', models.TextField(blank=True)),
                ('plan_badges', models.TextField(blank=True, help_text='One line per plan badge. Format: code|badge. Supported codes: basic, standard, multibranch, pro.')),
                ('plan_descriptions', models.TextField(blank=True, help_text='One line per plan description. Format: code|description. Supported codes: basic, standard, multibranch, pro.')),
                ('faq_items', models.TextField(blank=True, help_text='One line per FAQ item.')),
                ('money_back', models.CharField(blank=True, max_length=255)),
                ('closing_cta', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['language'],
            },
        ),
    ]
