# Generated by Codex on 2026-02-17

from django.db import migrations


def seed_marketing_content(apps, schema_editor):
    HomePageContent = apps.get_model("core", "HomePageContent")
    FeaturesPageContent = apps.get_model("core", "FeaturesPageContent")
    PricingPageContent = apps.get_model("core", "PricingPageContent")

    defaults = {
        "ar": {
            "home": {
                "title": "قد مطعمك بذكاء",
                "subtitle": "منصة موحدة لإدارة الطلبات والمخزون والتقارير.",
            },
            "features": {
                "title": "حلول ذكية لنمو أعمالك",
                "subtitle": "نربط الكاشير والمخزون وفريق العمل في بيئة تشغيل واحدة.",
            },
            "pricing": {
                "title": "اختر الباقة الأنسب لمشروعك",
                "subtitle": "باقات مرنة تبدأ من تشغيل فرع واحد حتى إدارة عدة فروع.",
            },
        },
        "en": {
            "home": {
                "title": "Run your restaurant with confidence",
                "subtitle": "One platform for orders, inventory, and reporting.",
            },
            "features": {
                "title": "Smart solutions for restaurant growth",
                "subtitle": "Connect POS, stock, staff, and analytics in one flow.",
            },
            "pricing": {
                "title": "Choose the right plan for your growth",
                "subtitle": "Flexible plans from single-branch to multi-branch operations.",
            },
        },
    }

    for language, values in defaults.items():
        HomePageContent.objects.get_or_create(
            language=language,
            defaults={
                "title": values["home"]["title"],
                "subtitle": values["home"]["subtitle"],
            },
        )
        FeaturesPageContent.objects.get_or_create(
            language=language,
            defaults={
                "title": values["features"]["title"],
                "subtitle": values["features"]["subtitle"],
            },
        )
        PricingPageContent.objects.get_or_create(
            language=language,
            defaults={
                "title": values["pricing"]["title"],
                "subtitle": values["pricing"]["subtitle"],
            },
        )


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_featurespagecontent_homepagecontent_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_marketing_content, noop_reverse),
    ]
