# Generated by Django 6.0.2 on 2026-03-02 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_leadrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadrequest',
            name='contact_method',
            field=models.CharField(blank=True, choices=[('phone', 'Phone'), ('email', 'Email'), ('whatsapp', 'WhatsApp')], max_length=16),
        ),
        migrations.AddField(
            model_name='leadrequest',
            name='inquiry_category',
            field=models.CharField(blank=True, choices=[('sales', 'Sales'), ('pricing', 'Pricing'), ('support', 'Support'), ('partnership', 'Partnership'), ('other', 'Other')], max_length=24),
        ),
        migrations.AddField(
            model_name='leadrequest',
            name='preferred_time',
            field=models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], max_length=16),
        ),
    ]
