# Generated by Django 6.0.2 on 2026-03-02 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_leadrequest_contact_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(choices=[('ar', 'Arabic'), ('en', 'English')], default='ar', max_length=8)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField(blank=True)),
                ('cta_text', models.CharField(blank=True, max_length=120)),
                ('cta_url', models.CharField(blank=True, max_length=240)),
                ('image_path', models.CharField(blank=True, help_text='Static path or full URL. Example: img/hero-slide-1.png', max_length=240)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Marketing Slide',
                'verbose_name_plural': 'Marketing Slides',
                'ordering': ['order', 'id'],
            },
        ),
    ]
