ROLE_SYSTEM_OWNER = "SystemOwner"
ROLE_SYSTEM_ADMIN = "SystemAdmin"
ROLE_CONTENT_MANAGER = "ContentManager"
ROLE_RESTAURANT_OWNER = "RestaurantOwner"
ROLE_BRANCH_MANAGER = "BranchManager"
ROLE_ACCOUNTANT = "Accountant"
ROLE_INVENTORY_MANAGER = "InventoryManager"
ROLE_CASHIER = "Cashier"
ROLE_KITCHEN_STAFF = "KitchenStaff"

ALL_GROUP_ROLES = [
    ROLE_SYSTEM_OWNER,
    ROLE_SYSTEM_ADMIN,
    ROLE_CONTENT_MANAGER,
    ROLE_RESTAURANT_OWNER,
    ROLE_BRANCH_MANAGER,
    ROLE_ACCOUNTANT,
    ROLE_INVENTORY_MANAGER,
    ROLE_CASHIER,
    ROLE_KITCHEN_STAFF,
]

BRANCH_SCOPED_ROLES = {
    ROLE_BRANCH_MANAGER,
    ROLE_INVENTORY_MANAGER,
    ROLE_CASHIER,
    ROLE_KITCHEN_STAFF,
}

PLAN_BASIC = "basic"
PLAN_STANDARD = "standard"
PLAN_MULTIBRANCH = "multibranch"
PLAN_PRO = "pro"

FEATURE_BRANCHES_LIMIT = "branches_limit"
FEATURE_ADVANCED_INVENTORY = "advanced_inventory"
FEATURE_RECIPES = "recipes"
FEATURE_BRANCH_COMPARISON = "branch_comparison"
FEATURE_HR_MODULE = "hr_module"
FEATURE_ACCOUNTING_MODULE = "accounting_module"
FEATURE_EXPORT_REPORTS = "export_reports"
FEATURE_ADVANCED_DASHBOARD = "advanced_dashboard"
FEATURE_KDS_SCREEN = "kds_screen"

PLAN_FEATURE_PRESET_A = {
    PLAN_BASIC: {
        FEATURE_BRANCHES_LIMIT: 1,
        FEATURE_ADVANCED_INVENTORY: False,
        FEATURE_RECIPES: False,
        FEATURE_BRANCH_COMPARISON: False,
        FEATURE_HR_MODULE: False,
        FEATURE_ACCOUNTING_MODULE: False,
        FEATURE_EXPORT_REPORTS: False,
        FEATURE_ADVANCED_DASHBOARD: False,
        FEATURE_KDS_SCREEN: False,
    },
    PLAN_STANDARD: {
        FEATURE_BRANCHES_LIMIT: 1,
        FEATURE_ADVANCED_INVENTORY: True,
        FEATURE_RECIPES: True,
        FEATURE_BRANCH_COMPARISON: False,
        FEATURE_HR_MODULE: False,
        FEATURE_ACCOUNTING_MODULE: False,
        FEATURE_EXPORT_REPORTS: True,
        FEATURE_ADVANCED_DASHBOARD: False,
        FEATURE_KDS_SCREEN: False,
    },
    PLAN_MULTIBRANCH: {
        FEATURE_BRANCHES_LIMIT: 5,
        FEATURE_ADVANCED_INVENTORY: True,
        FEATURE_RECIPES: True,
        FEATURE_BRANCH_COMPARISON: True,
        FEATURE_HR_MODULE: False,
        FEATURE_ACCOUNTING_MODULE: False,
        FEATURE_EXPORT_REPORTS: True,
        FEATURE_ADVANCED_DASHBOARD: False,
        FEATURE_KDS_SCREEN: True,
    },
    PLAN_PRO: {
        FEATURE_BRANCHES_LIMIT: -1,
        FEATURE_ADVANCED_INVENTORY: True,
        FEATURE_RECIPES: True,
        FEATURE_BRANCH_COMPARISON: True,
        FEATURE_HR_MODULE: True,
        FEATURE_ACCOUNTING_MODULE: True,
        FEATURE_EXPORT_REPORTS: True,
        FEATURE_ADVANCED_DASHBOARD: True,
        FEATURE_KDS_SCREEN: True,
    },
}
