# Generated by Django 6.0.2 on 2026-02-24 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchprinterconfig',
            name='delivery_printer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_configs', to='printing.printer'),
        ),
        migrations.AlterField(
            model_name='printjob',
            name='template_type',
            field=models.CharField(choices=[('customer', 'Customer Receipt'), ('kitchen', 'Kitchen Receipt'), ('delivery', 'Delivery Receipt')], max_length=16),
        ),
        migrations.AlterField(
            model_name='printtemplate',
            name='code',
            field=models.CharField(choices=[('customer', 'Customer'), ('kitchen', 'Kitchen'), ('delivery', 'Delivery')], max_length=32),
        ),
    ]
