# Generated by Django 6.0.2 on 2026-02-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('backup_type', models.CharField(choices=[('auto', 'Automated'), ('manual', 'Manual')], default='auto', max_length=16)),
                ('storage_backend', models.CharField(default='local', max_length=16)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('file_size', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
